name: lista_de_la_compra_http_server
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  drift: 2.26.0
  nsd: 4.0.3
  http: 1.3.0
  sqlite3: 2.7.6





dev_dependencies:
  build_runner: ^2.5.4
  drift_dev: ^2.26.1
  lints: ^5.0.0
  test: ^1.24.0
